package com.osmp4j.osm.features

object Barrier : Feature<Barrier>("barrier") {
    val BLOCK = value("block")
    val BOLLARD = value("bollard")
    val BORDER_CONTROL = value("border_control")
    val BUMP_GATE = value("bump_gate")
    val BUS_TRAP = value("bus_trap")
    val CABLE_BARRIER = value("cable_barrier")
    val CATTLE_GRID = value("cattle_grid")
    val CHAIN = value("chain")
    val CITY_WALL = value("city_wall")
    val CYCLE_BARRIER = value("cycle_barrier")
    val DEBRIS = value("debris")
    val DITCH = value("ditch")
    val ENTRANCE = value("entrance")
    val FENCE = value("fence")
    val FULL_HEIGHT_TURNSTILE = value("full-height_turnstile")
    val GATE = value("gate")
    val GUARD_RAIL = value("guard_rail")
    val HAMPSHIRE_GATE = value("hampshire_gate")
    val HANDRAIL = value("handrail")
    val HEDGE = value("hedge")
    val HEIGHT_RESTRICTOR = value("height_restrictor")
    val HORSE_STILE = value("horse_stile")
    val JERSEY_BARRIER = value("jersey_barrier")
    val KERB = value("kerb")
    val KISSING_GATE = value("kissing_gate")
    val LIFT_GATE = value("lift_gate")
    val LOG = value("log")
    val MOTORCYCLE_BARRIER = value("motorcycle_barrier")
    val RETAINING_WALL = value("retaining_wall")
    val ROPE = value("rope")
    val SALLY_PORT = value("sally_port")
    val SPIKES = value("spikes")
    val STILE = value("stile")
    val SUMP_BUSTER = value("sump_buster")
    val SWING_GATE = value("swing_gate")
    val TOLL_BOOTH = value("toll_booth")
    val TURNSTILE = value("turnstile")
    val WALL = value("wall")
    val YES = value("yes")

}