package com.osmp4j.osm.features

object Office : Feature<Office>("office") {
    val ACCOUNTANT = value("accountant")
    val ADOPTION_AGENCY = value("adoption_agency")
    val ADVERTISING_AGENCY = value("advertising_agency")
    val ARCHITECT = value("architect")
    val ASSOCIATION = value("association")
    val BAIL_BOND_AGENT = value("bail_bond_agent")
    val CHARITY = value("charity")
    val COMPANY = value("company")
    val COWORKING = value("coworking")
    val DIPLOMATIC = value("diplomatic")
    val EDUCATIONAL_INSTITUTION = value("educational_institution")
    val EMPLOYMENT_AGENCY = value("employment_agency")
    val ENERGY_SUPPLIER = value("energy_supplier")
    val ENGINEER = value("engineer")
    val ESTATE_AGENT = value("estate_agent")
    val FINANCIAL = value("financial")
    val FORESTRY = value("forestry")
    val FOUNDATION = value("foundation")
    val GEODESIST = value("geodesist")
    val GOVERNMENT = value("government")
    val GUIDE = value("guide")
    val HARBOUR_MASTER = value("harbour_master")
    val INSURANCE = value("insurance")
    val IT = value("it")
    val LAWYER = value("lawyer")
    val LOGISTICS = value("logistics")
    val MOVING_COMPANY = value("moving_company")
    val NEWSPAPER = value("newspaper")
    val NGO = value("ngo")
    val NOTARY = value("notary")
    val POLITICAL_PARTY = value("political_party")
    val PRIVATE_INVESTIGATOR = value("private_investigator")
    val PROPERTY_MANAGEMENT = value("property_management")
    val QUANGO = value("quango")
    val RELIGION = value("religion")
    val RESEARCH = value("research")
    val SURVEYOR = value("surveyor")
    val TAX = value("tax")
    val TAX_ADVISOR = value("tax_advisor")
    val TELECOMMUNICATION = value("telecommunication")
    val VISA = value("visa")
    val WATER_UTILITY = value("water_utility")
    val YES = value("yes")
}
