package com.osmp4j.osm.features

object OSMLeisure : OSMFeature<OSMLeisure>("leisure") {
    val ADULT_GAMING_CENTRE = value("adult_gaming_centre")
    val AMUSEMENT_ARCADE = value("amusement_arcade")
    val BEACH_RESORT = value("beach_resort")
    val BANDSTAND = value("bandstand")
    val BIRD_HIDE = value("bird_hide")
    val COMMON = value("common")
    val DANCE = value("dance")
    val DISC_GOLF_COURSE = value("disc_golf_course")
    val DOG_PARK = value("dog_park")
    val ESCAPE_GAME = value("escape_game")
    val FIREPIT = value("firepit")
    val FISHING = value("fishing")
    val FITNESS_CENTRE = value("fitness_centre")
    val FITNESS_STATION = value("fitness_station")
    val GARDEN = value("garden")
    val HACKERSPACE = value("hackerspace")
    val HORSE_RIDING = value("horse_riding")
    val ICE_RINK = value("ice_rink")
    val MARINA = value("marina")
    val MINIATURE_GOLF = value("miniature_golf")
    val NATURE_RESERVE = value("nature_reserve")
    val PARK = value("park")
    val PICNIC_TABLE = value("picnic_table")
    val PITCH = value("pitch")
    val PLAYGROUND = value("playground")
    val SLIPWAY = value("slipway")
    val SPORTS_CENTRE = value("sports_centre")
    val STADIUM = value("stadium")
    val SUMMER_CAMP = value("summer_camp")
    val SWIMMING_AREA = value("swimming_area")
    val SWIMMING_POOL = value("swimming_pool")
    val TRACK = value("track")
    val WATER_PARK = value("water_park")
}