package com.osmp4j.osm.features

object OSMLanduse : OSMFeature<OSMLanduse>("landuse") {
    val COMMERCIAL = value("commercial")
    val CONSTRUCTION = value("construction")
    val INDUSTRIAL = value("industrial")
    val RESIDENTIAL = value("residential")
    val RETAIL = value("retail")
    val ALLOTMENTS = value("allotments")
    val FARMLAND = value("farmland")
    val FARMYARD = value("farmyard")
    val FOREST = value("forest")
    val MEADOW = value("meadow")
    val ORCHARD = value("orchard")
    val VINEYARD = value("vineyard")
    val BASIN = value("basin")
    val BROWNFIELD = value("brownfield")
    val CEMETERY = value("cemetery")
    val CONSERVATION = value("conservation")
    val DEPOT = value("depot")
    val GARAGES = value("garages")
    val GRASS = value("grass")
    val GREENFIELD = value("greenfield")
    val GREENHOUSE_HORTICULTURE = value("greenhouse_horticulture")
    val LANDFILL = value("landfill")
    val MILITARY = value("military")
    val PEAT_CUTTING = value("peat_cutting")
    val PLANT_NURSERY = value("plant_nursery")
    val PORT = value("port")
    val QUARRY = value("quarry")
    val RAILWAY = value("railway")
    val RECREATION_GROUND = value("recreation_ground")
    val RELIGIOUS = value("religious")
    val RESERVOIR = value("reservoir")
    val SALT_POND = value("salt_pond")
    val VILLAGE_GREEN = value("village_green")
    val USER_DEFINED = value("user defined")
}