package com.osmp4j.osm.features

object Railway : Feature<Railway>("railway") {
    val ABANDONED = value("abandoned")
    val CONSTRUCTION = value("construction")
    val DISUSED = value("disused")
    val FUNICULAR = value("funicular")
    val LIGHT_RAIL = value("light_rail")
    val MINIATURE = value("miniature")
    val MONORAIL = value("monorail")
    val NARROW_GAUGE = value("narrow_gauge")
    val PRESERVED = value("preserved")
    val RAIL = value("rail")
    val SUBWAY = value("subway")
    val TRAM = value("tram")
    val HALT = value("halt")
    val PLATFORM = value("platform")
    val STATION = value("station")
    val SUBWAY_ENTRANCE = value("subway_entrance")
    val TRAM_STOP = value("tram_stop")
    val BUFFER_STOP = value("buffer_stop")
    val DERAIL = value("derail")
    val CROSSING = value("crossing")
    val LEVEL_CROSSING = value("level_crossing")
    val SIGNAL = value("signal")
    val SWITCH = value("switch")
    val RAILWAY_CROSSING = value("railway_crossing")
    val TURNTABLE = value("turntable")
    val ROUNDHOUSE = value("roundhouse")
    val TRAVERSER = value("traverser")
    val WASH = value("wash")
    val USER_DEFINED = value("user defined")

    val BRIDGE = attr("bridge")
    val CUTTING = attr("cutting")
    val ELECTRIFIED = attr("electrified")
    val EMBANKMENT = attr("embankment")
    val EMBEDDED_RAILS = attr("embedded_rails")
    val FREQUENCY = attr("frequency")
    val RAILWAY_TRACK_REF = attr("railway:track_ref")
    val TRACKS = attr("tracks")
    val TUNNEL = attr("tunnel")
    val USAGE = attr("usage")
    val VOLTAGE = attr("voltage")
}
